<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QLPIVJU" failures="1" tests="8" name="Testler.day3" time="0.034" errors="0" timestamp="2022-09-19T19:17:51 TRT" skipped="1">
  <testcase classname="Testler.day3" name="APIcarLoan" time="0.001">
    <skipped/>
  </testcase> <!-- APIcarLoan -->
  <system-out/>
  <testcase classname="Testler.day3" name="MobileLogin" time="0.001"/>
  <system-out/>
  <testcase classname="Testler.day3" name="ApLogin" time="0.002"/>
  <system-out/>
  <testcase classname="Testler.day3" name="MobileLogin" time="0.001"/>
  <system-out/>
  <testcase classname="Testler.day3" name="MobileLogOut" time="0.009"/>
  <system-out/>
  <testcase classname="Testler.day3" name="MobileSignin" time="0.001"/>
  <system-out/>
  <testcase classname="Testler.day3" name="webLogin" time="0.018">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Testler.day3.webLogin(day3.java:13)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- webLogin -->
  <system-out/>
  <testcase classname="Testler.day3" name="MobileLogin" time="0.001"/>
  <system-out/>
</testsuite> <!-- Testler.day3 -->
